version: '3.9'
services:
  impostor-db:
    image: postgres:17
    container_name: brawltracker-db
    ports:
      - "3838:5432"
    environment:
      POSTGRES_DB: brawltracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - impostor-db-data:/var/lib/postgresql/data
volumes:
  impostor-db-data:
